"""AnnData-native reconstruction of selected SPATA2 spatial utilities."""

from ._core import (
    SpatialData,
    as_micrometer,
    as_pixel,
    containsSpatialOutliers,
    containsTissueOutline,
    contains_spatial_outliers,
    contains_tissue_outline,
    createSpatialData,
    create_spatial_data,
    extract_variables,
    get_coords_df,
    get_coords_center,
    get_coords_mtr,
    get_coords_range,
    get_tissue_outline_df,
    getCoordsCenter,
    getCoordsDf,
    getCoordsMtr,
    getCoordsRange,
    getFeatureDf,
    getTissueOutlineDf,
    identify_spatial_outliers,
    identify_tissue_outline,
    identifySpatialOutliers,
    identifyTissueOutline,
    is_outlier,
    join_with_variables,
    pixels_to_unit,
    remove_spatial_outliers,
    removeSpatialOutliers,
    unit_to_pixels,
)
from .fixtures import create_spata2_fixture

spata_get_coords = get_coords_df
spata_identify_spatial_outliers = identify_spatial_outliers
spata_identify_tissue_outline = identify_tissue_outline

__all__ = [
    "SpatialData",
    "get_coords_df",
    "get_coords_mtr",
    "get_coords_range",
    "get_coords_center",
    "extract_variables",
    "join_with_variables",
    "identify_tissue_outline",
    "get_tissue_outline_df",
    "contains_tissue_outline",
    "identify_spatial_outliers",
    "remove_spatial_outliers",
    "contains_spatial_outliers",
    "pixels_to_unit",
    "unit_to_pixels",
    "is_outlier",
    "create_spatial_data",
    "getCoordsDf",
    "getCoordsMtr",
    "getCoordsRange",
    "getCoordsCenter",
    "getFeatureDf",
    "identifyTissueOutline",
    "getTissueOutlineDf",
    "containsTissueOutline",
    "identifySpatialOutliers",
    "removeSpatialOutliers",
    "containsSpatialOutliers",
    "createSpatialData",
    "as_pixel",
    "as_micrometer",
    "spata_get_coords",
    "spata_identify_spatial_outliers",
    "spata_identify_tissue_outline",
    "create_spata2_fixture",
]

__version__ = "0.1.0"
